apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot-app
  labels:
    app: java-springboot
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: java-springboot
  template:
    metadata:
      labels:
        app: java-springboot
    spec:
      containers:
      - name: java-springboot-container
        image: vikasprince/java-app 
        ports:
        - containerPort: 8080  
        
---
apiVersion: v1
kind: Service
metadata:
  name: java-springboot-service
spec:
  type: LoadBalancer 
  selector:
    app: java-springboot
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080
